name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Which tag?
        type: string
        default: 'v4.2.1'
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [amd64, arm64]
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          path: 'repository'
          ref: ${{ inputs.tag }}
          fetch-depth: 0
      - id: setup_qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.architecture }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.12.1
          platforms: linux/${{ matrix.architecture }}
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: greenclip
      #  id: docker_build_greenclip
      #  uses: docker/build-push-action@v3
      #  with:
      #    push: true
      #    platforms: linux/${{ matrix.architecture }}
      #    tags: ghcr.io/${{ github.repository_owner }}/greenclip:latest-${{ matrix.architecture }}
      #    cache-from: type=gha
      #    cache-to: type=gha,mode=max
      - name: Build "greenclip"
        working-directory: repository
        run: |
          # list files for debugging
          ls -la
          pwd
          # build the binary
          docker run \
            --rm \
            --platform='linux/${{ matrix.architecture }}' \
            -e TARGETARCH=${{ matrix.architecture }} \
            -v "$(pwd):$(pwd)" \
            --workdir="$(pwd)" \
            'glcr.b-data.ch/ghc/ghc-musl:9.6.2' \
              ./build.bash
          # rename the binary for current architecture
          cp \
            ./dist/greenclip \
            ./../greenclip-${{ matrix.architecture }}
      - uses: actions/upload-artifact@v4
        with:
          name: greenclip-${{ matrix.architecture }}
          path: greenclip-${{ matrix.architecture }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.tag }}
          artifacts: greenclip-${{ matrix.architecture }}
          draft: true
